blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/motsu131/c100_task/issues/new?template=custom.md&projects=kaitas%2FToDo%2F1&labels=ToDo
